language: node_js
node_js:
  - "node"
script:
  - "npm run build"
cache:
  directories:
    - "node_modules"
deploy:
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: releases
    local_dir: dist
    skip_cleanup: true
    api-key: $GITHUB_TOKEN
    file: monogatari.js
    on:
      tags: true